const data = [
    {
        "breeds": [],
        "id": "18l",
        "url": "https://cdn2.thecatapi.com/images/18l.gif",
        "width": 500,
        "height": 287
    },
    {
        "breeds": [],
        "id": "1lc",
        "url": "https://cdn2.thecatapi.com/images/1lc.jpg",
        "width": 446,
        "height": 500
    },
    {
        "breeds": [],
        "id": "1te",
        "url": "https://cdn2.thecatapi.com/images/1te.gif",
        "width": 166,
        "height": 141,
        favorite: true
    },
    {
        "breeds": [],
        "id": "2d9",
        "url": "https://cdn2.thecatapi.com/images/2d9.jpg",
        "width": 580,
        "height": 417
    },
    {
        "breeds": [],
        "id": "3ee",
        "url": "https://cdn2.thecatapi.com/images/3ee.jpg",
        "width": 500,
        "height": 332,
        favorite:true
    },
    {
        "breeds": [],
        "id": "3ql",
        "url": "https://cdn2.thecatapi.com/images/3ql.jpg",
        "width": 458,
        "height": 640
    },
    {
        "breeds": [
            {
                "weight": {
                    "imperial": "5 - 9",
                    "metric": "2 - 4"
                },
                "id": "munc",
                "name": "Munchkin",
                "vetstreet_url": "http://www.vetstreet.com/cats/munchkin",
                "temperament": "Agile, Easy Going, Intelligent, Playful",
                "origin": "United States",
                "country_codes": "US",
                "country_code": "US",
                "description": "The Munchkin is an outgoing cat who enjoys being handled. She has lots of energy and is faster and more agile than she looks. The shortness of their legs does not seem to interfere with their running and leaping abilities.",
                "life_span": "10 - 15",
                "indoor": 0,
                "lap": 1,
                "alt_names": "",
                "adaptability": 5,
                "affection_level": 5,
                "child_friendly": 4,
                "dog_friendly": 5,
                "energy_level": 4,
                "grooming": 2,
                "health_issues": 3,
                "intelligence": 5,
                "shedding_level": 3,
                "social_needs": 5,
                "stranger_friendly": 5,
                "vocalisation": 3,
                "experimental": 0,
                "hairless": 0,
                "natural": 0,
                "rare": 0,
                "rex": 0,
                "suppressed_tail": 0,
                "short_legs": 1,
                "wikipedia_url": "https://en.wikipedia.org/wiki/Munchkin_(cat)",
                "hypoallergenic": 0,
                "reference_image_id": "j5cVSqLer"
            }
        ],
        "id": "LxcLIxuVT",
        "url": "https://cdn2.thecatapi.com/images/LxcLIxuVT.jpg",
        "width": 1671,
        "height": 912
    },
    {
        "breeds": [
            {
                "weight": {
                    "imperial": "5 - 11",
                    "metric": "2 - 5"
                },
                "id": "sfol",
                "name": "Scottish Fold",
                "cfa_url": "http://cfa.org/Breeds/BreedsSthruT/ScottishFold.aspx",
                "vetstreet_url": "http://www.vetstreet.com/cats/scottish-fold-highland-fold",
                "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/scottish-fold",
                "temperament": "Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving",
                "origin": "United Kingdom",
                "country_codes": "GB",
                "country_code": "GB",
                "description": "The Scottish Fold is a sweet, charming breed. She is an easy cat to live with and to care for. She is affectionate and is comfortable with all members of her family. Her tail should be handled gently. Folds are known for sleeping on their backs, and for sitting with their legs stretched out and their paws on their belly. This is called the \"Buddha Position\".",
                "life_span": "11 - 14",
                "indoor": 0,
                "alt_names": "Scot Fold",
                "adaptability": 5,
                "affection_level": 5,
                "child_friendly": 4,
                "dog_friendly": 5,
                "energy_level": 3,
                "grooming": 1,
                "health_issues": 4,
                "intelligence": 3,
                "shedding_level": 3,
                "social_needs": 3,
                "stranger_friendly": 3,
                "vocalisation": 1,
                "experimental": 0,
                "hairless": 0,
                "natural": 0,
                "rare": 0,
                "rex": 0,
                "suppressed_tail": 0,
                "short_legs": 0,
                "wikipedia_url": "https://en.wikipedia.org/wiki/Scottish_Fold",
                "hypoallergenic": 0,
                "reference_image_id": "o9t0LDcsa"
            }
        ],
        "id": "iI8IyNGDg",
        "url": "https://cdn2.thecatapi.com/images/iI8IyNGDg.jpg",
        "width": 1680,
        "height": 1050
    }
]

export const names = ['Adônis',
'Dionísio',
'Odin',
'Afrodite',
'Eir',
'Pegasus',
'Agata',
'Freia',
'Perseu',
'Akila',
'Frigga',
'Perséfone',
'Amon',
'Hades',
'Rá',
'Anúbis',
'Helena',
'Ragnar',
'Apolo',
'Loki',
'Selene',
'Aquiles',
'Hermes',
'Seth',
'Ares',
'Horus',
'Thor',
'Artémis',
'Iris',
'Tróia',
'Atena',
'Lilith',
'Tyr',
'Athos',
'Maya',
'Vali',
'Brutus',
'Mitra',
'Zelo',
'César',
'Netuno',
'Zeus' ]

export default data;